module.exports = {
  mySidebar: [
    'index',
  {
      type: 'category',
      label: 'Multi Instance',
      collapsed: true,
      items: [
        'Multi Instance Background',  
        'Multi Instance Schedules',
        'Multi Instance Exercise 1',
        'Multiple Instance Properties',
        'Multi Instance Exercise 2',
        'Multi Instance Exercise 3',   
        'Duplicate Instance Property',
        'Multi Instance Exercise 4',
        'Multi Instance Schedule Limitation',
        'Fully Qualified SI Property Name',
        'Multi Instance Exercise 5',
        'Multi Instance Hurdles In Updating SI Property',
        'Multi Instance Lab A',
        'Multi Instance Jobs',
        'Multi Instance Exercise 6',
        'Multi Instance Jobs Limitations',
        'Multi Instance Exercise 7',
        'Multi Instance Machine Groups',
        'Multi Instance Exercise 8',
        'Multi Instance JI Property',
        'Multi Instance Lab B',
        'Multi Instance Lab C',
        'Schedule Named Instances',
        'Multi Instance Exercise 9',
        'Cross Schedule Instance Dependencies',
        'SubSchedules Schedule Instance Property',
        'Multi Instance Exercise 10',
        'Multi Instance Exercise 11',
        'SubSchedules External Events',
        'Multi Instance Exercise 12',
        'Multi Instance Lab D'  
      ],
  },
  {
    type: 'category',
    label: 'Expressions',
    collapsed: true,
    items: [
      'Expressions Overview',
      'Expressions Exercise 1',
      'Expressions Arithmetic',
      'Expressions Exercise 2',
      'Expressions Arithmetic With Properties',
      'Expressions Substrings',
      'Expressions Exercise 3',
      'Expressions Length',
      'Expressions Exercise 4',
      'Expressions Property in Property Value',
      'Expressions Exercise 5',
      'Expressions Property in Property Name',
      'Expressions Exercise 6',
      'Expressions Lab A',
      'Expressions Dependencies',
      'Expressions Dependencies Threshold Replacement',
      'Expressions Exercise 7',
      'Expressions Multiple Time Windows',
      'Expressions Exercise 8A',
      'Expressions Exercise 8B',
      'Expressions Lab B',
      'Expressions Expression Based Events',
      'Expressions Exercise 9',
      'Expressions Self Service Expressions',
      'Expressions Exercise 10',
      'Expressions Lab C'
    ],
},
{
  type: 'category',
  label: 'Special Topics',
  collapsed: true,
  items: [
    'Advanced Failure Criteria',
    'Special Topics Exercise 1',
    'Job Output Parsing',
    'Special Topics Exercise 2',
    'Advanced Frequencies',
    'Special Topics Exercise 3',
    'Frequency Dependencies And Events',
    'Special Topics Exercise 4',
    'Advanced Date Calculation',
    'Special Topics Exercise 5',
    'Chronoman',
    'Special Topics Exercise 6',
    'Calendar ADD Events',
    'Special Topics Exercise 7',
  ],
},
  ],
};
