module.exports = {
  mySidebar: [
    'index',
  {
      type: 'category',
      label: 'Multi Instance Schedules',
      collapsed: true,
      items: [
        'Multi Instance Background',
        'Multi Instance Schedules',
        'Multi Instance Exercise 1',
        'Multiple Instance Properties',
        'Multi Instance Exercise 2',
        'Duplicate Instance Property',
        'Multi Instance Exercise 3',   
        'Multi Instance Exercise 4',
        'Multi Instance Schedule Limitation',
        'Fully Qualified SI Property Name',
        'Multi Instance Exercise 5',
        'Multi Instance Hurdles In Updating SI Property',
        'Multi Instance Lab A',
      ]
  },
  {
      type: 'category',
      label: 'Multi Instance Jobs',
      collapsed: true,
      items: [
        'Multi Instance Jobs',
        'Multi Instance Exercise 6',
        'Multi Instance JI Property',
        'Multi Instance Jobs Limitations',
        'Multi Instance Exercise 7',
        'Multi Instance Machine Groups',
        'Multi Instance Exercise 8',
        'Multi Instance Lab B',
      ]
  },
  {
      type: 'category',
      label: 'Multi Instance Named Instances',
      collapsed: true,
      items: [
        'Named Instance Schedules',
        'Named Instance Creation',
        'Named Instance Patterns',
        'Named Instance Exception Rules',
        'Named Instance Dependencies and Limitations',
        'Multi Instance Exercise 9',
      ]
    },
    {
      type: 'category',
      label: 'Multi Instance SubSchedules',
      collapsed: true,
      items: [
        'SubSchedule Background',
        'SubSchedule Instance Property',
        'Multi Instance Exercise 10',
        'Multi Instance Exercise 11',
        'SubSchedule External Events',
        'Multi Instance Exercise 12',
        'Multi Instance Lab C',
      ],
  },
  {
    type: 'category',
    label: 'Property Expressions',
    collapsed: true,
    items: [
      'Expressions Overview',
      'Expressions Upper and Lower',
      'Expressions Exercise 1',
      'Expressions Arithmetic',
//    'Expressions Arithmetic With Properties',
      'Expressions Exercise 2',
      'Expressions Substrings',
      'Expressions Exercise 3',
      'Expressions Length',
      'Expressions Exercise 4',
      'Expressions Property in Property Value',
      'Expressions Exercise 5',
      'Expressions Property in Property Name',
      'Expressions Exercise 6',
//      'Expressions Lab A',
    ],
  },
  {
    type: 'category',
    label: 'Expression Dependencies',
    collapsed: true,
    items: [
      'Expressions Dependencies',
      'Expressions Dependencies Threshold Replacement',
      'Expressions Exercise 7',
      'Expressions Multiple Time Windows',
//      'Expressions Lab B',
      'Expressions Exercise 8',
      'Expressions Expression Based Events',
      'Expressions Exercise 9',
      'Expressions Exercise 10',
      'Expressions Self Service Expressions',
      'Expressions Exercise 11',
//      'Expressions Lab C',
    ],
},
{
  type: 'category',
  label: 'Special Topics',
  collapsed: true,
  items: [
    'Advanced Failure Criteria',
    'Special Topics Exercise 1',
    'Job Output Parsing',
    'Special Topics Exercise 2',
    'Advanced Frequencies',
    'Special Topics Exercise 3',
    'Frequency Dependencies And Events',
    'Special Topics Exercise 4',
    'Calendar ADD Events',
    'Advanced Date Calculation',
    'Special Topics Exercise 5',
  ],
},
{  
  type: 'link',
  label: 'Student Feedback Survey',
  href: 'https://forms.office.com/r/qkfrtxKmGA',
},
  ],
};
