name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
      - run: azcopy_v10 copy 'build/*' '${{ secrets.TRAINING_STORAGE_URL }}/${{ secrets.CONTENT_PATH }}?${{ secrets.TRAINING_STORAGE_KEY }}' --recursive
